name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: write
  issues: write
  pages: write
jobs:
  static-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Copy custom assets and data to site output
        run: |
          mkdir -p site/__sapper__/export/custom
          mkdir -p site/__sapper__/export/data
          rm -rf site/__sapper__/export/custom/uptime-history.css
          rm -rf site/__sapper__/export/custom/uptime-history.js
          cp -v custom/uptime-history.js site/__sapper__/export/custom/uptime-history.js
          cp -v custom/uptime-history.css site/__sapper__/export/custom/uptime-history.css
          cp -v history/summary.json site/__sapper__/export/data/summary.json
          echo "=== custom ==="
          ls -la site/__sapper__/export/custom/
          echo "=== data ==="
          ls -la site/__sapper__/export/data/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/__sapper__/export
          cname: status.storyly.io
